from enum import StrEnum


class WebsocketMessageTypes(StrEnum):
    AGENT_DATA = 'AGENT_DATA'
    UPDATE_CALLS = 'UPDATE_CALLS'
    CONNECT_CALLS = 'CONNECT_CALLS'
    SYSTEM_RESOURCES_MONITORING = 'SYSTEM_RESOURCES_MONITORING'
    CALL_COUNT = 'CALL_COUNT'


class WebsocketConnectionTypes(StrEnum):
    DASHBOARD = 'DASHBOARD'
    OPERATOR_PANEL = 'OPERATOR_PANEL'
