"""set_null on_delete

Revision ID: a1a6a8beadf7
Revises: 366966be997d
Create Date: 2026-05-18 15:45:57.684763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1a6a8beadf7'
down_revision: Union[str, None] = '366966be997d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('webgram_agents_user_uuid_fkey'), 'webgram_agents', type_='foreignkey')
    op.create_foreign_key(None, 'webgram_agents', 'webgram_users', ['user_uuid'], ['user_uuid'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'webgram_agents', type_='foreignkey')
    op.create_foreign_key(op.f('webgram_agents_user_uuid_fkey'), 'webgram_agents', 'webgram_users', ['user_uuid'], ['user_uuid'])
    # ### end Alembic commands ###
