"""create queue table

Revision ID: 907e6748b7fe
Revises: fe2ae91287a5
Create Date: 2026-04-06 20:07:27.177806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '907e6748b7fe'
down_revision: Union[str, None] = 'fe2ae91287a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webgram_queues',
    sa.Column('queue_uuid', sa.Uuid(), nullable=False),
    sa.Column('queue_name', sa.String(length=255), nullable=False),
    sa.Column('queue_number', sa.String(length=255), nullable=False),
    sa.Column('domain_uuid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['domain_uuid'], ['webgram_domains.domain_uuid'], ),
    sa.PrimaryKeyConstraint('queue_uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webgram_queues')
    # ### end Alembic commands ###
