"""create tiers

Revision ID: 3cd1cb2d3426
Revises: 907e6748b7fe
Create Date: 2026-04-21 19:21:45.266184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cd1cb2d3426'
down_revision: Union[str, None] = '907e6748b7fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webgram_tiers',
    sa.Column('tier_uuid', sa.Uuid(), nullable=False),
    sa.Column('agent_uuid', sa.UUID(), nullable=False),
    sa.Column('queue_uuid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agent_uuid'], ['webgram_agents.agent_uuid'], ),
    sa.ForeignKeyConstraint(['queue_uuid'], ['webgram_queues.queue_uuid'], ),
    sa.PrimaryKeyConstraint('tier_uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webgram_tiers')
    # ### end Alembic commands ###
