"""add domain table

Revision ID: ef7909b6cb31
Revises: e2e773310eee
Create Date: 2026-04-02 13:00:13.689069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef7909b6cb31'
down_revision: Union[str, None] = 'e2e773310eee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webgram_domains',
    sa.Column('domain_uuid', sa.Uuid(), nullable=False),
    sa.Column('domain_name', sa.String(length=255), nullable=False),
    sa.Column('domain_enabled', sa.Boolean(), nullable=False),
    sa.Column('domain_description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('domain_uuid'),
    sa.UniqueConstraint('domain_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webgram_domains')
    # ### end Alembic commands ###
