"""add numbers_table

Revision ID: b2ba51d7ba45
Revises: 3cd1cb2d3426
Create Date: 2026-04-29 10:54:04.678118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2ba51d7ba45'
down_revision: Union[str, None] = '3cd1cb2d3426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
