"""add numbers_table

Revision ID: 366966be997d
Revises: 3cd1cb2d3426
Create Date: 2026-04-29 11:08:49.670727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '366966be997d'
down_revision: Union[str, None] = '3cd1cb2d3426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webgram_numbers',
    sa.Column('number_uuid', sa.Uuid(), nullable=False),
    sa.Column('number_name', sa.String(length=255), nullable=False),
    sa.Column('number_number', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('number_uuid'),
    sa.UniqueConstraint('number_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webgram_numbers')
    # ### end Alembic commands ###
