"""create agent table

Revision ID: f163d2a369f3
Revises: ef7909b6cb31
Create Date: 2026-04-06 17:26:07.369860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f163d2a369f3'
down_revision: Union[str, None] = 'ef7909b6cb31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webgram_agents',
    sa.Column('agent_uuid', sa.Uuid(), nullable=False),
    sa.Column('agent_name', sa.String(length=255), nullable=False),
    sa.Column('agent_number', sa.String(length=255), nullable=False),
    sa.Column('agent_password', sa.String(length=255), nullable=True),
    sa.Column('domain_uuid', sa.UUID(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=True),
    sa.Column('agent_status', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['domain_uuid'], ['webgram_domains.domain_uuid'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['webgram_users.user_uuid'], ),
    sa.PrimaryKeyConstraint('agent_uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webgram_agents')
    # ### end Alembic commands ###
