"""initial

Revision ID: e2e773310eee
Revises: 
Create Date: 2026-03-31 12:49:23.646252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2e773310eee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webgram_roles',
    sa.Column('role_uuid', sa.Uuid(), nullable=False),
    sa.Column('role_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('role_uuid'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('webgram_users',
    sa.Column('user_uuid', sa.Uuid(), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('user_password', sa.String(length=500), nullable=False),
    sa.Column('role_uuid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_uuid'], ['webgram_roles.role_uuid'], ),
    sa.PrimaryKeyConstraint('user_uuid'),
    sa.UniqueConstraint('user_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webgram_users')
    op.drop_table('webgram_roles')
    # ### end Alembic commands ###
