"""create extension table

Revision ID: fe2ae91287a5
Revises: f163d2a369f3
Create Date: 2026-04-06 19:18:02.174778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe2ae91287a5'
down_revision: Union[str, None] = 'f163d2a369f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webgram_extensions',
    sa.Column('extension_uuid', sa.Uuid(), nullable=False),
    sa.Column('extension_number', sa.String(length=255), nullable=False),
    sa.Column('extension_password', sa.String(length=255), nullable=True),
    sa.Column('caller_id_name', sa.String(length=255), nullable=True),
    sa.Column('caller_id_number', sa.String(length=255), nullable=True),
    sa.Column('domain_uuid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['domain_uuid'], ['webgram_domains.domain_uuid'], ),
    sa.PrimaryKeyConstraint('extension_uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webgram_extensions')
    # ### end Alembic commands ###
